### PR TITLE
Ana/fix glitch for multi denom send modal

### LINKED ISSUE #179: Fix TableInvoice glitch for multi denom send
The first denom appears repeated for some reason

image

### PR DESCRIPTION
**Pull request by Bitcoinera**
Closes #179 

Working on it

### CODE REVIEW

**Comment by Bitcoinera** [comment]
Looking good

image

What doesn't actually work is sending IBC tokens, but this is probably because some IBC code for sending is missing

**Comment by Bitcoinera** [comment]
Ready! :dancers: :woman_dancing:

File: store/data.js [hunk 1]
```diff
@@ -212,7 +212,9 @@ export const actions = {
   ) {
     try {
       commit('setTransactionsLoading', true)
-      const transactions = await api.getTransactions(address, pageNumber)
+      // Deactivate for now as not working on Stargate
+      // const transactions = await api.getTransactions(address, pageNumber)
+      const transactions = await []
```
Comment (faboweb) [inline store/data.js:217]:
```suggestion
      const transactions = await api.getTransactions(address, pageNumber)
```

let's not check that in

File: components/portfolio/BalanceRow.vue [hunk 2]
```diff
@@ -64,7 +64,10 @@
       </div>
     </td>
 
-    <LazySendModal ref="SendModal" :denoms="[balance.denom]" />
+    <LazySendModal
```
Comment (faboweb) [inline components/portfolio/BalanceRow.vue:67]: in theory this element should go to the parent component and be triggered by an event. no need to have x send modal elements in there

Comment (Bitcoinera) [reply components/portfolio/BalanceRow.vue:67]: what do you mean?

File: network.js [hunk 3]
```diff
@@ -15,6 +15,12 @@ export default {
       chainToViewConversionFactor: 1e-6,
       icon: `https://lunie.fra1.digitaloceanspaces.com/network-icons/cosmos.png`,
     },
+    {
+      viewDenom: 'slippers',
+      chainDenom: /^ibc*/g,
+      chainToViewConversionFactor: 1e-6,
+      icon: `https://lunie.fra1.digitaloceanspaces.com/network-icons/cosmos.png`,
+    },
```
Comment (faboweb) [inline network.js:23]: why? that doesn't look feasable. what about other denoms from IBC??

Comment (Bitcoinera) [reply network.js:23]: we can have a reges as viewDenom, any string is good to go

File: components/portfolio/BalanceRow.vue (hunk 2 above)
Comment (faboweb) [reply components/portfolio/BalanceRow.vue:67]: every balance row imports a lazysendmodal. why? there is only one open at a time.
therefor it would be better to move the sendmodal to the balances component and handle a click on a send button to trigger an event that bubbles to the balances component and opens the modal. but for another PR I guess. it becomes more obvious as you need to pass the balances from the parent now to this child component

File: network.js (hunk 3 above)
Comment (faboweb) [reply network.js:23]: > what about other denoms from IBC??
please remove

Comment (Bitcoinera) [reply network.js:23]: This is what I mean. You can have unlimited tokens. This is the problem I'm aiming to approach here

File: components/portfolio/BalanceRow.vue (hunk 2 above)
Comment (Bitcoinera) [reply components/portfolio/BalanceRow.vue:67]: Yes, it makes much more sense to do it like that

File: network.js (hunk 3 above)
Comment (faboweb) [reply network.js:23]: you are not solving this problem. you are just calling them all `slippers`. ergo: please remove this non fix

Comment (Bitcoinera) [reply network.js:23]: Yes, and I said replace `viewDenom` by another regex as the fix. Doing that

**Comment by Bitcoinera** [comment]
Argg, I need this merged

File: components/portfolio/BalanceRow.vue (hunk 2 above)
Comment (jbibla) [reply components/portfolio/BalanceRow.vue:67]: @Bitcoinera open a new issue for this refactor

**Comment by faboweb** [comment]
Remove the slippers lookup

File: store/data.js (hunk 1 above)
Comment (faboweb) [reply store/data.js]: Ping

File: components/portfolio/BalanceRow.vue (hunk 2 above)
Comment (Bitcoinera) [reply components/portfolio/BalanceRow.vue:70]: oki :+1:
