### PR TITLE
fixes for proposal and validator profile

### LINKED ISSUE #276: Proposal description styling is exceeding borders
image (5)

### PR DESCRIPTION
**Pull request by jbibla**
closes #276

### CODE REVIEW

File: components/governance/ProposalDescription.vue [hunk 1]
```diff
@@ -6,13 +6,7 @@
...
       <h4>Description</h4>
       <div class="description">
-        <pre
-          v-if="
-            proposal.type === `PARAMETER_CHANGE` || proposal.type === `TREASURY`
-          "
-          >{{ proposal.description }}</pre
-        >
-        <p v-else>{{ proposal.description }}</p>
+        <pre>{{ proposal.description }}</pre>
```
Comment (faboweb) [inline components/governance/ProposalDescription.vue:9]: sure? there was a purpose in not using a pre I remember

Comment (jbibla) [reply components/governance/ProposalDescription.vue:9]: yeah it's ok. plaintext proposals might be "nicer" without a `pre` wrapper but it's not really a big deal and i didn't feel like making sure all the styles worked properly for `p` tags - so `pre` is ok for now.

Comment (faboweb) [reply components/governance/ProposalDescription.vue:9]: lazy...
